language: java

jdk:
  - oraclejdk8
  - openjdk8

cache:
    directories:
    - $HOME/.m2

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=3.2.5"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
